### ISSUE TITLE
update Tudio.US/API/AUTH

### ISSUE THREAD

**Issue by obrien-k** [orphic-inc/ruby-orphic-cli#15]
The client must send this token in the Authorization header when making requests to protected resources:
Authorization: Bearer <token>

The Bearer authentication scheme was originally created as part of OAuth 2.0 in RFC-6750 but is sometimes also used on its own.

**Comment by wuubi** [comment]
As a neo: Currently when a neo sends 'spools tudio.us' nothing happens.

**Comment by QuasarChains** [comment]
Totally

**Comment by obrien-k** [comment]
lost domain, closing
